=== bearsunday/BEAR.EventSourcing/var/schema/cart.get.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "cart.get.json",
  "type": "object",
  "title": "Cart Detail Response",
  "required": ["id", "total_price", "create_date", "update_date"],
  "properties": {
    "id": {"type": "integer"},
    "cart_key": {"type": ["string", "null"]},
    "pre_order_id": {"type": ["string", "null"]},
    "total_price": {"type": "number"},
    "delivery_fee_total": {"type": "number"},
    "sort_no": {"type": ["integer", "null"]},
    "create_date": {"type": "string", "format": "date-time"},
    "update_date": {"type": "string", "format": "date-time"},
    "customer": {"$ref": "#/definitions/Reference"},
    "cart_items": {"type": "array", "items": {"$ref": "#/definitions/Reference"}}
  },
  "definitions": {
    "Reference": {
      "type": "object",
      "required": ["id", "name"],
      "properties": {"id": {"type": "integer"}, "name": {"type": "string"}}
    }
  }
}

=== bearsunday/BEAR.EventSourcing/var/fake/cart/item.json
{
    "id": 1,
    "cart_key": null,
    "pre_order_id": "サンプルpre_order_id",
    "total_price": 1000,
    "delivery_fee_total": 1000,
    "sort_no": 1,
    "create_date": "2024-01-01T00:00:00+09:00",
    "update_date": "2024-01-01T00:00:00+09:00",
    "customer": {
        "id": 1,
        "name": "サンプルCustomer"
    },
    "cart_items": [
        {
            "id": 1,
            "name": "サンプルCartItem"
        }
    ]
}
