=== bearsunday/BEAR.EventSourcing/var/schema/member.get.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "member.get.json",
  "type": "object",
  "title": "Member Detail Response",
  "required": ["id", "name", "login_id", "create_date", "update_date"],
  "properties": {
    "id": {"type": "integer"},
    "name": {"type": "string"},
    "login_id": {"type": "string"},
    "department": {"type": ["string", "null"]},
    "password": {"type": ["string", "null"]},
    "salt": {"type": ["string", "null"]},
    "sort_no": {"type": ["integer", "null"]},
    "two_factor_auth_key": {"type": ["string", "null"]},
    "two_factor_auth_enabled": {"type": "boolean"},
    "create_date": {"type": "string", "format": "date-time"},
    "update_date": {"type": "string", "format": "date-time"},
    "login_date": {"type": ["string", "null"], "format": "date-time"},
    "work": {"$ref": "#/definitions/Reference"},
    "authority": {"$ref": "#/definitions/Reference"},
    "member": {"$ref": "#/definitions/Reference"}
  },
  "definitions": {
    "Reference": {
      "type": "object",
      "required": ["id", "name"],
      "properties": {"id": {"type": "integer"}, "name": {"type": "string"}}
    }
  }
}

=== bearsunday/BEAR.EventSourcing/var/fake/member/item.json
{
    "id": 1,
    "name": "管理者",
    "login_id": "admin",
    "department": "サンプルdepartment",
    "password": "サンプルpassword",
    "salt": "サンプルsalt",
    "sort_no": 1,
    "two_factor_auth_key": "サンプルtwo_factor_auth_key",
    "two_factor_auth_enabled": false,
    "create_date": "2024-01-01T00:00:00+09:00",
    "update_date": "2024-01-01T00:00:00+09:00",
    "login_date": null,
    "work": {
        "id": 1,
        "name": "サンプルWork"
    },
    "authority": {
        "id": 1,
        "name": "サンプルAuthority"
    },
    "member": {
        "id": 1,
        "name": "サンプルMember"
    }
}
